version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    post_create_environment:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
    post_install:
      - uv sync --only-group doc
sphinx:
  configuration: docs/conf.py
