environment:
  matrix:
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27"

build: off

before_test:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip tox wheel virtualenv setuptools"

test_script:
  - "%PYTHON%\\python.exe -m tox -e standard"
