version: 2.1

shared: &shared_linux
  steps:
    - run:
        name: Install required runtime dependencies
        command: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git dnsutils
          pip install --upgrade tox
    - checkout
    - run:
        name: Execute tests through tox
        command: tox
  environment:
    - TOXENV=light,standard
    - PYTEST_ADDOPTS=--numprocesses 8
  
shared: &shared_windows
  steps:
    - run:
        name: Install required runtime dependencies
        command:
          choco install --no-progress -y python --version "$PYTHON_VERSION"
          python -m pip install tox
    - checkout
    - run:
        name: Execute tests through tox
        command: python -m tox
  environment:
    - TOXENV=light,standard
    - PYTEST_ADDOPTS=--numprocesses 8

jobs:
  "python-2.7-linux":
    <<: *shared_linux
    docker:
      - image: python:2.7-slim
  "python-3.5-linux":
    <<: *shared_linux
    docker:
      - image: python:3.5-slim
  "python-3.6-linux":
    <<: *shared_linux
    docker:
      - image: python:3.6-slim
  "python-3.7-cover-linux":
    <<: *shared_linux
    docker:
      - image: python:3.7-slim
    environment:
      - TOXENV=light,cover
  "lint-linux":
    <<: *shared_linux
    docker:
      - image: python:3.7-slim
    environment:
      - TOXENV=lint
  "python-3.7-windows":
    <<: *shared_windows
    executor: win/vs2019
    environment:
      - PYTHON_VERSION=3.7.4

workflows:
  version: 2
  build:
    jobs:
      - "python-2.7-linux"
      - "python-3.5-linux"
      - "python-3.6-linux"
      - "python-3.7-cover-linux"
      - "lint-linux"
      - "python-3.7-windows"