version: 2

dependencies: &install_dependencies
  command: |
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git dnsutils
    pip install --upgrade tox
  name: Install required runtime dependencies
  
shared: &shared
  steps:
    - run:
        <<: *install_dependencies
    - checkout
    - run:
        name: Execute tests through tox
        command: tox
  environment:
    - TOXENV=light,standard
    - PYTEST_ADDOPTS=--numprocesses 8

jobs:
  "python-2.7":
    <<: *shared
    docker:
      - image: python:2.7-slim
  "python-3.4":
    <<: *shared
    docker:
      - image: python:3.4-slim
  "python-3.5":
    <<: *shared
    docker:
      - image: python:3.5-slim
  "python-3.6":
    <<: *shared
    docker:
      - image: python:3.6-slim
  "python-3.7-cover":
    <<: *shared
    docker:
      - image: python:3.7-slim
    environment:
      - TOXENV=light,cover
  "lint":
    <<: *shared
    docker:
      - image: python:3.7-slim
    environment:
      - TOXENV=lint

workflows:
  version: 2
  build:
    jobs:
      - "python-2.7"
      - "python-3.4"
      - "python-3.5"
      - "python-3.6"
      - "python-3.7-cover"
      - "lint"